// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyiayeqqhtudybquvprh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5aWF5ZXFxaHR1ZHlicXV2cHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzc3OTQsImV4cCI6MjA2MzkxMzc5NH0.Dj982t1d06mWqdkGhOkH7BQc7qvWUFAcHEtDkoDUCEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});